<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Created By</name>
   <tag></tag>
   <elementGuidId>5fbf9820-36f7-490c-a36b-8ff467241975</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='selIKK_chzn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selIKK_chzn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chzn-container chzn-container-single chzn-container-active</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RIS SystemUsersCharinee SenanarongWeeraya ThawinbunKorapat WongananchaiPareenard KlanruangsaengSuphannika Chuichai RIS SystemChatsaran ParaksaRIS SystemLukkhana ThaipermpolMugarin SrathongkaewAdmin CRMCPichamonch Jira crmtraineePaiwan MangsombatI-Tech SystemPiyawat PolsriSathaphon TepnatimSupornpan PimlaPrapaporn KhamkhoonSumit BoonpipatpiroonRattapong WongniponChaiyachet LimkanjanaLaphadrada LertnilakanSiraporn khamguanPatiphat LaohachainanonThitima LomlungkaNisarat ChanrodSarinee PhutooyaJanejit SuebsinWilaiporn SukeemitPakinai PhummarinCharinee WachirakositAnussara NamtachanKritsawat VaneesornKomdetch ThongchueaboonmaNararit BoonyaritThanakorn PansomPraphan VivattananukulSirintip Tien-ngernMalik SuwandeePrasert BinsalemSomphob SamaisukRapeewan AnukanSompoth InrungSurat TiyanuchitThanawut MahatrakulrangsriChairat KwangthongSomkiat OrnsomkritcParaporn BuathongSarunchana MesukkulakarnSuvimol PromdontrePholsan WainitraJintapa BoonruangOrawan JarungsutjaritkulNuttharin HomruenIttichai ThongcharoenPiyapong PongsiriVorathep Techa-amnueysukSapap ChangjaruekPichit VisetsiriWarut MarongsriSuwat ArvutpanyakulTeerapong TiwattanonPaisan JaikongKamol SilachariyaSinchai ChaicharoenthongPantip SirivatanakosolChanate LeelafauengsinNased SalemNarinpach PakkamSystem Administrator CRM-CJohn SmithSomchai NoranaraphantFuengfah SalangsingAunchalee NaluanChayaporn PandiHochin KongKidsana KidakasakulPacharanat WorachayanunPimonpun ChintaroNitthakan ChuaypulPakhinee SripunPiyanit Kham-imPanjamaporn SuwanwijitMonrudee KovitvoravutVarhasookh AnakitbumrungSirichai ChamnansetBenjapol BenjanakManassanan MaiphetAtipong SrichandeeKunakon OranrattanasakulKritsanawitch NaowaratTossawach ChancherngkitPrapavis ChumsiensirikunNirin TiwsikaresSirichai PichaibunditkunYossunphol WetvarittusKhoamchit Tang-ngamjittsririPattharawee TewatthatanontSaranya SokumaJakkrit DiowvilaiRujipatt DuangamornYupin RatsamesaiPatpong LaoprasertsakThitiworn KongthippayagSoradet JiravichalertSupanut KunupakarnNaphapat PengmaneeKemmarat NumsomboonAniwat RuenroengVasupol PokasirisinUchot KosrettaruchNorrawat KittiviriyaratKiatisak JorradolGidraphar ImsamaiPoonyanuch DisaphanthanamKoranitsiri DarachMeena WaneewanichRangsan ChitbenchakunKamoltip HongtongTaweeporn KetkonNoppadon TangnaitrisorranaRinrada WilaiwathanakornNuttharee SeetijanSupravee MekdumrongraksJunsri OsathanondaChadawan OpponPrawvanich SiritanyanurakPhiphatthanaphong ChanamorakotphaisanMeathawat  WilaiwathanakornMontree WichansawagulWasin KudithalertVaraporn LorjarassuriyaPanisara ChutikarnjanadechathornChotiros MuenkaewThanakorn WichansawagulJednipat ChansopeekulNaruemol WongkomechanPussadee DecharunArissara SompornsukswatPhuthai DaengsinghParul PoonthirakulSongvit TantikarnJesada JirapassapongPurichaya KovitvoravutKamonwan KhayaiyaemPatitta RueangyingSaengdao WisessakPongsapak PichitanansakulSayarm SuesattayanonMetta SingkrajomeTanthima AnanvorakijPromporn SringamKamolrat AmnajsirimongkolNatcha ThanakornjiropastJirayut LupkittaroMarisa KhamphuanSarahong MuangdedNapaphan KhajornklinRamida PromsainSomchit ParayonthSongyot ChinvithayapornSiwaporn KeratimakulPatcharinporn UsaWaroonrat RattanatarosKanit KittiphattaraphonAlisa SuwanbubphaAmolrada WoranuchThanyatorn RuedechRatana SutthijareanpornKalaya JaitumMontawan WainitraNantawit PlubjanVimonludee PhanchoocherdPanunat OngartPanchita JiratabhumiwatWiwat LertwatanasakWA ScanThippawan NontananandApisara TangsukulVisart ChinvichaSomchai PakbunditkulPatcharin IamimsartSanti ChaisilaparungruangWannee SoontorntepvarakulRangsan RuamyooRatree ReungkeiawPeerawat SeangsuriNatthaphol SuntudkarnAmporn KitpitukSoradit RatanasatianSrisilp ChamnanharnHikari MoritaMiki YoshidaMito KawaharaPitra LimpivesMakiko AsadaThanda JirapatkornkulSirisub PunchangtongGroupsMarketing GroupSupport GroupTeam Selling</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selIKK_chzn&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='selIKK_chzn']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='EditView']/table[6]/tbody/tr/td[2]/div/span/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[6]/tbody/tr/td[2]/div/span/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
